title: Signaturgruppen Broker documentation
theme: just-the-docs

url: https://signaturgruppen-a-s.github.io/signaturgruppen-broker-documentation
logo: "/assets/broker-logo.png"
favicon_ico: "/assets/favicon.ico"

aux_links:
  Template Repository: https://github.com/Signaturgruppen-A-S/signaturgruppen-broker-documentation
